server:
  port: 80
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: zero
    password: 123456
    url: jdbc:mysql://localhost:3306/imoocbootscala?useSSL=false
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
